project:
  type: website
  output-dir: "."
  
website:
  title: "Josh Lefkowicz"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Classwork
        href: danl-200-cw-10.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
  
left:
  - text: Project
  href: project.qmd
  - text: Blog
  href: blog-listing.qmd
  - text: Homeowrk
    href: hw.qmd
left:
  - text: "Projects"
    menu:
      - project_1.qmd
      - project_2.qmd

    
  

