---
title: "Classwork 10"
format: html
editor: visual

toc: true
toc-title: "Table of Contents"
toc-depth: 2
number-sections: true

fig-width: 9

execute:
  code-tools: true
  message: false
  warning: false
---

```{r}
#| eval: true
#| include: false
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)

theme_set(theme_ipsum()+
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          )
```

```{r}
#| results: asis
#| echo: false
rmarkdown::paged_table(billboard) 
```

#Question 1: Billboard Charts

```{r}
billboard <- read_csv('https://bcdanl.github.io/data/billboard.csv')
```

### Without Facets

```{r}

```

### With Facets

```{r}
q1a <- billboard %>% 
  pivot_longer(cols = wk1:wk76,
               names_to ="week",
               values_to= "ranking") %>% 
  filter(week %in% c('wk1','wk2','wk3'))
```

```{r}

  
```
